# Generated by Django 5.1.3 on 2025-01-30 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuidePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='本文')),
                ('category', models.CharField(choices=[('strategy', '攻略'), ('anecdote', '小ネタ'), ('pr', 'PR')], max_length=50, verbose_name='カテゴリー')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('image', models.ImageField(upload_to='images/')),
                ('thumbnail', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='名前')),
                ('compost_at', models.DateTimeField(auto_now_add=True, verbose_name='コメント日時')),
                ('compost', models.TextField(verbose_name='コメント')),
                ('guidepost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='guide.guidepost')),
            ],
        ),
    ]
